#!/usr/bin/env bash
set -ex
EXTENSIONS="jupyterlab-toc@0.2.1 @jupyter-widgets/jupyterlab-manager@0.35.0 @jupyterlab/github@0.7.2"

for ext in $EXTENSIONS; do
  jupyter labextension install $ext --no-build || echo "whatever, $ext"
done

jupyter labextension list

jupyter lab build --dev

importnb-install
